server:
  port: 8080

spring:
  datasource:
    name: shop
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&useUnicode=true&characterEncodin=UTF-8&
          autoReconnect=true&serverTimeZone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bf1127bf1127
